apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "isk-printer.fullname" . }}-database
  labels:
{{ include "isk-printer.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.database.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "isk-printer.name" . }}-database
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ include "isk-printer.fullname" . }}-database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "isk-printer.name" . }}-database
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-database
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          command: ["mongod"]
          args: ["--journal"]
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          ports:
            - name: http
              containerPort: {{ .Values.database.service.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
          resources:
            {{- toYaml .Values.resources.database | nindent 12 }}
          volumeMounts:
            - name: {{ .Chart.Name }}-database-volume
              mountPath: {{ .Values.database.volume.mountPath }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Chart.Name }}-database-volume
        labels:
          app.kubernetes.io/name: {{ include "isk-printer.name" . }}-database
          app.kubernetes.io/instance: {{ .Release.Name }}
      spec:
        # storageClassName: "fast"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.database.volume.capacity }}
