apiVersion: v1
kind: Service
metadata:
  name: {{ include "isk-printer.fullname" . }}-database
  labels:
{{ include "isk-printer.labels" . | indent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.port }}
      protocol: TCP
      name: mongodb
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "isk-printer.name" . }}-database
    app.kubernetes.io/instance: {{ .Release.Name }}
