apiVersion: v1
kind: Secret
metadata:
  name: {{ include "isk-printer.fullname" . }}-database
  labels:
{{ include "isk-printer.labels" . | indent 4 }}
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ required "Argument --set MONGO_INITDB_ROOT_USERNAME=<mongo-initdb-root-username> is required." .Values.MONGO_INITDB_ROOT_USERNAME | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ required "Argument --set MONGO_INITDB_ROOT_PASSWORD=<mongo-initdb-root-password> is required." .Values.MONGO_INITDB_ROOT_PASSWORD | b64enc }}
