steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/cameronhudson8/IskPrinter-Site']
  
  # Google Cloud Build calls this file as if it existed at the repository root,
  # so we must refer to the Dockerfile specified in './frontend'.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/isk-printer/github.com/cameronhudson8/iskprinter-site/frontend:$REVISION_ID', './frontend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/isk-printer/github.com/cameronhudson8/iskprinter-site/frontend:$REVISION_ID']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - -n
  - $_NAMESPACE
  - set
  - image
  - deployment
  - frontend
  - frontend=gcr.io/isk-printer/github.com/cameronhudson8/iskprinter-site/frontend:$REVISION_ID
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'