version: "3.7"
services:

  db:
    image: mysql
    env_file:
      - ./db/.env
    tty: true
    volumes:
     - db_data:/var/lib/mysql

  iskprinter_site:
    build:
      context: ./iskprinter_site
      dockerfile: Dockerfile.prod
    environment:
      - WEBROOT=/var/www/html/public

    tty: true
    ports:
      - "380:80"
      - "3443:443"





  # eve_sde_db:
  #   build:
  #     context: ./eve_sde_db
  #   env_file:
  #     - ./eve_sde_db/.env
  #   tty: true
  #   expose:
  #     - 3306



volumes:




  db_data:
    driver_opts:
      device: /databases/iskprinter.com
      o: bind





networks:
  default:
    name: reverse_proxy