version: "3.7"
services:

  iskprinter_site:
    build:
      context: ./iskprinter_site
      dockerfile: Dockerfile.dev
    environment:
      - WEBROOT=/var/www/html/frontend/dist/frontend
      - PHP_ERRORS_STDERR=true
    tty: true
    ports:
      - "380:80"
      - "3443:443"
    volumes:
      - iskprinter_site_data:/var/www/html

  iskprinter_db:
    image: mysql
    env_file:
      - ./iskprinter_db/.env
    tty: true
    expose:
      - 3306
    volumes:
     - iskprinter_db_data:/var/lib/mysql

  # eve_sde_db:
  #   build:
  #     context: ./eve_sde_db
  #   env_file:
  #     - ./eve_sde_db/.env
  #   tty: true
  #   expose:
  #     - 3306
    # volumes:
    #  - eve_sde_db_data:/var/lib/mysql

volumes:
  iskprinter_site_data:
    driver_opts:
      device: ${PWD}/iskprinter_site
      o: bind
  iskprinter_db_data:
    driver_opts:
      device: /databases/iskprinter.com
      o: bind
  # eve_sde_db_data:
  #   driver_opts:
  #     device: /databases/eve-sde
  #     o: bind
      
networks:
  default:
    name: reverse_proxy