apiVersion: v1
kind: Service
metadata:
  name: {{ include "isk-printer.fullname" . }}-backend
  labels:
{{ include "isk-printer.labels" . | indent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "isk-printer.name" . }}-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
