apiVersion: v1
kind: Secret
metadata:
  name: tls
  namespace: iskprinter-prod # Since this certificate is not for wildcard subdomains, it will only be used in one namespace.
data:
  tls.crt: <base64 encoded cert>
  tls.key: <base64 encoded key>
type: kubernetes.io/tls