apiVersion: v1
kind: Secret
metadata:
  name: {{ include "isk-printer.fullname" . }}-backend
  labels:
{{ include "isk-printer.labels" . | indent 4 }}
type: Opaque
data:
  CLIENT_ID: {{ required "Argument --set CLIENT_ID=<client-id> is required." .Values.CLIENT_ID | b64enc }}
  CLIENT_SECRET: {{ required "Argument --set CLIENT_SECRET=<client-secret> is required." .Values.CLIENT_SECRET | b64enc }}
