apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: reverse-proxy
  namespace: iskprinter-prod
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: iskprinter.com # Creating a rule for www.iskprinter.com will not work, because the SSL certificate is only for iskprinter.com.
    http:
      paths:
      - path: /api
        backend:
          serviceName: backend
          servicePort: 3000
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
  tls:
  - secretName: tls
