apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "isk-printer.fullname" . }}-frontend
  labels:
{{ include "isk-printer.labels" . | indent 4 }}
data:
  BACKEND_URL: "{{ required "Argument --set HOSTNAME=<url> is required." .Values.HOSTNAME }}/api"
