apiVersion: v1
kind: Secret
metadata:
  name: {{ include "isk-printer.fullname" . }}-tls
  labels:
{{ include "isk-printer.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "Argument --set TLS_CRT_BASE64=<tls-cert-base64> is required." .Values.TLS_CRT_BASE64 }}
  tls.key: {{ required "Argument --set TLS_KEY_BASE64=<tls-key-base64> is required." .Values.TLS_KEY_BASE64 }}
