apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: tls-iskprinter.com
  labels:
{{ include "isk-printer.labels" . | indent 4 }}
data:
  tls.crt: <base64 encoded cert>
  tls.key: <base64 encoded key>
