# Default values for isk-printer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:
  replicaCount: 1
  image:
    repository: docker.io/cameronhudson8/isk-printer-backend
    tag: latest
    pullPolicy: Always
  containerPort: 
  service:
    type: ClusterIP
    port: 3000

frontend:
  replicaCount: 1
  image:
    repository: docker.io/cameronhudson8/isk-printer-frontend
    tag: f8b89d3
    pullPolicy: Always
  containerPort: 
  service:
    type: ClusterIP
    port: 80

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: iskprinter.com
      paths:
      - path: /api
        backend:
          serviceName: backend
          servicePort: 3000
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
  tls:
   - secretName: tls-iskprinter.com

resources:
  default:
    limits:
      cpu: &defaultCpuLimit 0
      memory: &defaultMemoryLimit 128Mi
    requests:
      cpu: &defaultCpuRequest 0
      memory: &defaultMemoryRequest 128Mi
  backend:
    limits:
      cpu: *defaultCpuLimit
      memory: 64Mi
    requests:
      cpu: *defaultCpuRequest
      memory: 64Mi
  frontend:
    limits:
      cpu: *defaultCpuLimit
      memory: 16Mi
    requests:
      cpu: *defaultCpuRequest
      memory: 16Mi

nodeSelector: {}

tolerations: []

affinity: {}
