# Default values for isk-printer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

frontend:
  replicaCount: 1
  image:
    repository: docker.io/cameronhudson8/isk-printer-frontend
    tag: f99cead
    pullPolicy: Always
  service:
    type: ClusterIP  # default
    port: 80

backend:
  replicaCount: 1
  image:
    repository: docker.io/cameronhudson8/isk-printer-backend
    tag: f99cead
    pullPolicy: Always
  service:
    type: ClusterIP  # default
    port: 3000

database:
  replicaCount: 1
  image:
    repository: mongo
    tag: 4.4.1-bionic
    pullPolicy: IfNotPresent  # default
  service:
    type: ClusterIP  # default
    port: 27017
  volume:
    capacity: 8Gi
    mountPath: /data/db

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: iskprinter.com
      paths:
      - path: /api
        backend:
          serviceName: backend
          servicePort: 3000
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
  tls:
   - secretName: tls-iskprinter.com

resources:
  default:
    limits:
      cpu: &defaultCpuLimit 0
      memory: &defaultMemoryLimit 128Mi
    requests:
      cpu: &defaultCpuRequest 0
      memory: &defaultMemoryRequest 128Mi
  backend:
    limits:
      cpu: *defaultCpuLimit
      memory: *defaultMemoryLimit
    requests:
      cpu: *defaultCpuRequest
      memory: *defaultMemoryRequest
  frontend:
    limits:
      cpu: *defaultCpuLimit
      memory: *defaultMemoryLimit
    requests:
      cpu: *defaultCpuRequest
      memory: *defaultMemoryRequest
  database:
    limits:
      cpu: *defaultCpuLimit
      memory: *defaultMemoryLimit
    requests:
      cpu: *defaultCpuRequest
      memory: *defaultMemoryRequest

nodeSelector: {}

tolerations: []

affinity: {}
