# Default values for isk-printer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

frontend:
  replicaCount: 1
  image:
    repository: docker.io/cameronhudson8/isk-printer-frontend
    tag: 9d26b9f
    pullPolicy: Always
  service:
    type: ClusterIP  # default
    port: 80
  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 128Mi

backend:
  replicaCount: 1
  image:
    repository: docker.io/cameronhudson8/isk-printer-backend
    tag: 9d26b9f
    pullPolicy: Always
  service:
    type: ClusterIP  # default
    port: 3000
  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 128Mi

database:
  replicaCount: 1
  image:
    repository: mongo
    tag: 4.4.1-bionic
    pullPolicy: IfNotPresent  # default
  service:
    type: ClusterIP  # default
    port: 27017
  volume:
    capacity: 8Gi
    mountPath: /data/db
  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 128Mi

weeklyDownload:
  image:
    repository: docker.io/cameronhudson8/isk-printer-weekly-download
    tag: 9d26b9f
    pullPolicy: IfNotPresent  # default
  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 128Mi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: iskprinter.com
      paths:
      - path: /api
        backend:
          serviceName: backend
          servicePort: 3000
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
  tls:
   - secretName: tls-iskprinter.com

nodeSelector: {}

tolerations: []

affinity: {}
